---
- connection: local
  hosts: 127.0.0.1
  gather_facts: no
  tasks:
  - name: Prepare dist directory
    file:
      path: "{{ playbook_dir }}/dist/templates"
      state: directory

  - name: Generate RHEL 8 templates
    template:
      src: rhel7.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: server, memsize: "1G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: tiny, workload: desktop, memsize: "1G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: tiny, workload: highperformance, memsize: "1G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: small, workload: server, memsize: "2G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: small, workload: desktop, memsize: "2G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: small, workload: highperformance, memsize: "2G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: desktop, memsize: "4G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: medium, workload: highperformance, memsize: "4G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    - {flavor: large, workload: desktop, memsize: "8G", cpus: 2, iothreads: False, tablet: True}
    - {flavor: large, workload: highperformance, memsize: "8G", cpus: 2, iothreads: True, tablet: False}
    vars:
      os: rhel8
      icon: rhel
      password: redhat
      oslabels:
       - rhel8.0
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate RHEL 7 templates
    template:
      src: rhel7.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: server, memsize: "1G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: tiny, workload: desktop, memsize: "1G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: tiny, workload: highperformance, memsize: "1G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: small, workload: server, memsize: "2G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: small, workload: desktop, memsize: "2G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: small, workload: highperformance, memsize: "2G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: desktop, memsize: "4G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: medium, workload: highperformance, memsize: "4G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    - {flavor: large, workload: desktop, memsize: "8G", cpus: 2, iothreads: False, tablet: True}
    - {flavor: large, workload: highperformance, memsize: "8G", cpus: 2, iothreads: True, tablet: False}
    vars:
      os: rhel7
      icon: rhel
      password: redhat
      oslabels:
       - rhel7.0
       - rhel7.1
       - rhel7.2
       - rhel7.3
       - rhel7.4
       - rhel7.5
       - rhel7.6
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate RHEL 6 templates
    template:
      src: rhel6.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: server, memsize: "1G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: tiny, workload: desktop, memsize: "1G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: small, workload: server, memsize: "2G", cpus: 1, iothreads: False, tablet: False}    
    - {flavor: small, workload: desktop, memsize: "2G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: desktop, memsize: "4G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    - {flavor: large, workload: desktop, memsize: "8G", cpus: 2, iothreads: False, tablet: True}
    vars:
      os: rhel6
      icon: rhel
      password: redhat
      oslabels:
       - rhel6.0
       - rhel6.1
       - rhel6.2
       - rhel6.3
       - rhel6.4
       - rhel6.5
       - rhel6.6
       - rhel6.7
       - rhel6.8
       - rhel6.9
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate CentOS 8 templates
    template:
      src: centos7.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: server, memsize: "1G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: tiny, workload: desktop, memsize: "1G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: small, workload: server, memsize: "2G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: small, workload: desktop, memsize: "2G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: desktop, memsize: "4G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    - {flavor: large, workload: desktop, memsize: "8G", cpus: 2, iothreads: False, tablet: True}
    vars:
      os: centos8
      icon: centos
      password: centos
      oslabels:
       - centos8.0
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate CentOS 7 templates
    template:
      src: centos7.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: server, memsize: "1G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: tiny, workload: desktop, memsize: "1G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: small, workload: server, memsize: "2G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: small, workload: desktop, memsize: "2G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: desktop, memsize: "4G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    - {flavor: large, workload: desktop, memsize: "8G", cpus: 2, iothreads: False, tablet: True}
    vars:
      os: centos7
      icon: centos
      password: centos
      oslabels:
       - centos7.0
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate CentOS 6 templates
    template:
      src: centos6.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: server, memsize: "1G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: small, workload: server, memsize: "2G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    vars:
      os: centos6
      icon: centos
      password: centos
      oslabels:
       - centos6.0
       - centos6.1
       - centos6.2
       - centos6.3
       - centos6.4
       - centos6.5
       - centos6.6
       - centos6.7
       - centos6.8
       - centos6.9
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate Fedora templates
    template:
      src: fedora.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: desktop, memsize: "1G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: tiny, workload: server, memsize: "1G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: tiny, workload: highperformance, memsize: "1G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: small, workload: desktop, memsize: "2G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: small, workload: server, memsize: "2G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: small, workload: highperformance, memsize: "2G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: medium, workload: desktop, memsize: "4G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: highperformance, memsize: "4G", cpus: 1, iothreads: True, tablet: False}
    - {flavor: large, workload: desktop, memsize: "8G", cpus: 2, iothreads: False, tablet: True}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    - {flavor: large, workload: highperformance, memsize: "8G", cpus: 2, iothreads: True, tablet: False}
    vars:
      os: fedora
      icon: fedora
      password: fedora
      oslabels:
       - fedora26
       - fedora27
       - fedora28
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate OpenSUSE templates
    template:
      src: opensuse.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: server, memsize: "1G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: small, workload: server, memsize: "2G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    vars:
      os: opensuse
      icon: opensuse
      password: opensuse
      oslabels:
       - opensuse15.0
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate Ubuntu templates
    template:
      src: ubuntu.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: tiny, workload: desktop, memsize: "1G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: small, workload: desktop, memsize: "2G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: medium, workload: desktop, memsize: "4G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: large, workload: desktop, memsize: "8G", cpus: 2, iothreads: False, tablet: True}
    vars:
      cpumodel: Conroe
      os: ubuntu
      icon: ubuntu
      password: ubuntu
      oslabels:
       - ubuntu18.04
      osinfoname: "{{ oslabels[0] }}"

  - name: Generate Windows templates
    template:
      src: win2k12r2.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/win2k12r2-{{ item.workload }}-{{ item.flavor }}.yaml"
    with_items:
    - {flavor: medium, workload: server, memsize: "4G", cpus: 1, iothreads: False, tablet: False}
    - {flavor: medium, workload: desktop, memsize: "4G", cpus: 1, iothreads: False, tablet: True}
    - {flavor: large, workload: server, memsize: "8G", cpus: 2, iothreads: False, tablet: False}
    - {flavor: large, workload: desktop, memsize: "8G", cpus: 2, iothreads: False, tablet: True}
    vars:
      osinfoname: win2k12r2
