---
- connection: local
  hosts: 127.0.0.1
  gather_facts: no
  tasks:
  - name: Prepare dist directory
    file:
      path: "{{ playbook_dir }}/dist/templates"
      state: directory

  - name: Load RHEL 9 versions
    set_fact:
      rhel9_labels: "{{ lookup('osinfo', 'distro=rhel') |map(attribute='short_id') |select('match', '^rhel9\\.') |list |sort }}"

  - name: Generate RHEL 9 template
    template:
      src: rhel9.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/{{ os }}.yaml"
    vars:
      os: rhel9
      icon: rhel
      majorrelease: rhel9
      oslabels: "{{ rhel9_labels }}"
      osinfoname: "{{ oslabels[0] }}"
      cloudusername: cloud-user

  - name: Generate Windows 11 template
    template:
      src: windows11.tpl.yaml
      dest: "{{ playbook_dir }}/dist/templates/windows11.yaml"
    vars:
      osinfoname: win11