{% set version =  "0.13.0" %}
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: {{ os }}-{{ item.workload }}-{{ item.flavor }}-v{{ version }}
  annotations:
    openshift.io/display-name: "CentOS 6.0+ VM"
    description: >-
      Template for CentOS 6 VM or newer.
      A PVC with the CentOS disk image must be available.
    tags: "hidden,kubevirt,virtualmachine,linux,centos"

{% set diskbus = diskbus |default("sata") %}

{% include "_linux.yaml" %}

