{% set version =  "0.7.0" %}
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: {{ os }}-{{ item.workload }}-{{ item.flavor }}-v{{ version }}
  annotations:
    openshift.io/display-name: "Fedora 23+ VM"
    description: >-
      This template can be used to create a VM suitable for
      Fedora 23 and newer.
      The template assumes that a PVC is available which is providing the
      necessary Fedora disk image.

      Recommended disk image (needs to be converted to raw)
      https://download.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.qcow2
    tags: "hidden,kubevirt,virtualmachine,fedora,rhel"

{% include "_linux.yaml" %}

