{% set version =  "0.12.0" %}
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: {{ os }}-{{ item.workload }}-{{ item.flavor }}-v{{ version }}
  annotations:
    openshift.io/display-name: "OpenSUSE Leap 15.0 VM"
    description: >-
      Template for OpenSUSE Leap 15.0 VM.
      A PVC with the OpenSUSE disk image must be available.

      Recommended disk image (needs to be converted to raw)
      https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.0/images/
    tags: "hidden,kubevirt,virtualmachine,linux,opensuse"

{% include "_linux.yaml" %}
