{% set version =  "0.11.3" %}
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: {{ os }}-{{ item.workload }}-{{ item.flavor }}-v{{ version }}
  annotations:
    openshift.io/display-name: "Ubuntu 18.04 (Xenial Xerus) VM"
    description: >-
      Template for Ubuntu 18.04 (Xenial Xerus) VM.
      A PVC with the Ubuntu disk image must be available.

      Recommended disk image (needs to be converted to raw)
      http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    tags: "hidden,kubevirt,virtualmachine,ubuntu"

{% include "_linux.yaml" %}
