apiVersion: v1
kind: Template
metadata:
  name: win2k12r2-{{ item.workload }}-{{ item.flavor }}
  annotations:
    openshift.io/display-name: "Microsoft Windows Server 2012 R2 VM"
    description: >-
      This template can be used to create a VM suitable for
      Microsoft Windows Server 2012 R2.
      The template assumes that a PVC is available which is providing the
      necessary Windows disk image.
    tags: "kubevirt,virtualmachine,windows"
    iconClass: "icon-windows"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/kubevirt/common-templates"
    openshift.io/support-url: "https://github.com/kubevirt/common-templates/issues"
    template.openshift.io/bindable: "false"

    template.cnv.io/version: v1alpha1
    defaults.template.cnv.io/disk: rootdisk
    defaults.template.cnv.io/network: default
    template.cnv.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.resources.requests.memory
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks

    name.os.template.cnv.io/win2k12r2: {{ lookup('osinfo', 'win2k12r2').name }}
    name.os.template.cnv.io/win2k8r2: {{ lookup('osinfo', 'win2k8r2').name }}
    name.os.template.cnv.io/win2k8: {{ lookup('osinfo', 'win2k8').name }}
    name.os.template.cnv.io/win10: {{ lookup('osinfo', 'win10').name }}

  labels:
    os.template.cnv.io/win2k12r2: "true"
    os.template.cnv.io/win2k8r2: "true"
    os.template.cnv.io/win2k8: "true"
    os.template.cnv.io/win10: "true"
    workload.template.cnv.io/{{ item.workload }}: "true"
    flavor.template.cnv.io/{{ item.flavor }}: "true"
    template.cnv.io/type: "base"

objects:
- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    name: ${NAME}
    labels:
      vm.cnv.io/template: win2k12r2-{{ item.workload }}-{{ item.flavor }}
      app: ${NAME}
  spec:
    running: false
    template:
      spec:
        domain:
          clock:
            utc: {}
            timer:
              hpet:
                present: false
              pit:
                tickPolicy: delay
              rtc:
                tickPolicy: catchup
              hyperv: {}
          cpu:
            sockets: {{ item.cpus }}
            cores: 1
            threads: 1
          resources:
            requests:
              memory: {{ item.memsize }}
          features:
            acpi: {}
            apic: {}
            hyperv:
              relaxed: {}
              vapic: {}
              spinlocks:
                spinlocks: 8191
          devices:
            disks:
            - disk:
                bus: sata
              name: rootdisk
            interfaces:
            - bridge: {}
              model: e1000e
              name: default
        terminationGracePeriodSeconds: 0
        volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        networks:
        - name: default
          pod: {}

parameters:
- name: NAME
  description: VM name
  generate: expression
  from: "win2k12-[a-z0-9]{6}"
- name: PVCNAME
  description: Name of the PVC with the disk image
  required: true
