apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./2k12
  - ./2k12_virtio
  - ./2k16
  - ./2k16_virtio
  - ./2k19
  - ./2k19_virtio
  - ./10
  - ./10_virtio
  - ./11
  - ./11_virtio